### ISSUE TITLE
Cannot build the docker image

### ISSUE THREAD

**Issue by wmacgreg** [iarsystems/bx-docker#33]
When building the docker image using ./build ${BX_DOWNLOAD_URL##*/}, I get this error:

Dockerfile:33

--------------------
  31 |     # Copy the installer package from the Docker context to /tmp
  32 |     #
  33 | >>> COPY ${BX_PACKAGE_DEB}.deb /tmp
  34 |     
  35 |     #
--------------------

ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 8256c722-d7d1-4e22-a7f5-b7ff7836f9e3::1vxmacriwpdli7a6b4m2wqd4l: "/bxarm-9.60.3.deb.deb": not found

Changing line 33 to this:
  33 | >>> COPY ${BX_PACKAGE_DEB} /tmp

Fixed the problem

**Comment by felipe-iar** [comment]
Thanks. From the information you provided, it seems there is something wrong with `export BX_DOWNLOAD_URL=https://updates.iar.com/<redacted-url>/bxarm-9.60.3.deb`. The error message says `...d4l: " /bxarm-9.60.3.deb.deb not found`, which shows the package extension `.deb.deb` repeated. If you want to use our scripts the way it was composed, please review your settings otherwise also feel free to modify your scripts in case there is a different need for you.

Let us know if you need more information or feel free to close this issue.

**Comment by kfraasch** [comment]
@felipe-iar I am running into this as well. I am using the link provided to me in email screenshotted below

![image](https://github.com/user-attachments/assets/a91fc352-74d6-4057-8042-fde6c2427ccd)

**Comment by felipe-iar** [comment]
Thanks for reiterating on this issue. Tested the Scripts and Dockerfile from on a clean slate on a different system and was now to confirm the issue. Will be fixed soon.
